spring:
  application:
    # 应用名称
    name: ai-springboot

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/mental_health_assistant?useSSL=false&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        model: qwen3.6-plus


# 服务器端口
server:
  port: 1236
  servlet:
    # 上下文路径
    context-path: /api

# JWT 配置
jwt:
  # 密钥
  secret: MySecretKeyForJWT2025!@#$%^&*()_+SecureKeyHere
  # 24小时（毫秒）
  expiration: 86400000
  # 7天（毫秒）
  refresh-expiration: 604800000
  # token头部名称
  header: Authorization
  # token前缀
  token-prefix: "Bearer "